
name: 'bde_at3'
version: '1.0.0'
config-version: 2

profile: 'bde_at3'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:      
  - "target"
  - "dbt_packages"


models:
  bde_at3:
      datamart:
        +materialized: view 
        +schema: datamart
      warehouse:
        +materialized: table 
        +schema: warehouse
      staging:
        +materialized: view
        +schema: staging
      
