sources:
  - name: raw
    description: Raw data from GCP CSV files, loaded via airflow.
    database: postgres
    schema: raw

    tables:
      - name: census_g01
      - name: census_g02
      - name: lga_code
      - name: lga_suburb
      - name: listing